export type TransactionType = 'income' | 'expense' | 'savings_transfer' | 'transfer';

export type IncomeSource =
  | 'Uang Saku'
  | 'Kiriman Orang Tua'
  | 'Beasiswa'
  | 'Part-Time'
  | 'Freelance'
  | 'Organisasi/Event'
  | 'Bonus'
  | 'Lainnya';

export type ExpenseCategory =
  | 'Makanan'
  | 'Kos'
  | 'Listrik/Air'
  | 'Internet/Pulsa'
  | 'Transportasi'
  | 'Pendidikan'
  | 'Kesehatan'
  | 'Entertainment'
  | 'Nongkrong'
  | 'Shopping'
  | 'Subscription'
  | 'Tabungan'
  | 'Investasi'
  | 'Pembayaran Utang'
  | 'Lainnya';

export type PaymentMethod =
  | 'Tunai'
  | 'QRIS'
  | 'GoPay'
  | 'OVO'
  | 'ShopeePay'
  | 'DANA'
  | 'Transfer Bank'
  | 'Kartu Debit'
  | 'Lainnya';

export type ExpenseClassification = 'need' | 'want';

export type AccountType = 'cash' | 'bank' | 'ewallet' | 'other';

export interface Account {
  id: string;
  name: string;
  type: AccountType;
  balance: number;
  initialBalance?: number;
  accountNumber?: string;
  color?: string;
  icon?: string;
  isDefault?: boolean;
  createdAt: string;
}

export interface Transaction {
  id: string;
  date: string; // YYYY-MM-DD
  type: TransactionType;
  amount: number;
  category: ExpenseCategory | IncomeSource | string;
  paymentMethod?: PaymentMethod;
  accountId?: string;
  fromAccountId?: string;
  toAccountId?: string;
  classification?: ExpenseClassification;
  notes?: string;
  goalId?: string; // If contribution to or withdrawal from savings goal
  isRecurringInstance?: boolean;
  recurringId?: string;
  mood?: SpendingMood;
  receiptImage?: string;
  academicTag?: string;
  createdAt: string;
}

export type SpendingMood = 'rational' | 'impulsive' | 'stress' | 'reward' | 'fomo';

export interface MonthlyBudget {
  category: ExpenseCategory;
  monthlyLimit: number;
}

export interface CategoryBudgetStatus {
  category: ExpenseCategory;
  monthlyLimit: number;
  spent: number;
  remaining: number;
  percentageUsed: number;
  status: 'green' | 'yellow' | 'red';
}

export interface BudgetSummary {
  items: CategoryBudgetStatus[];
  totalBudget: number;
  totalSpent: number;
  totalRemaining: number;
  overallPercentage: number;
  overBudgetCount: number;
}

export interface SavingGoal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  targetDate: string; // YYYY-MM-DD
  categoryIcon: string;
  description?: string;
  isEmergencyFund?: boolean;
  academicType?: 'skripsi' | 'kkn' | 'magang' | 'lomba' | 'wisuda' | 'general';
  milestones?: { id: string; title: string; target: number; completed: boolean }[];
  createdAt: string;
}

export interface GoalContribution {
  id: string;
  goalId: string;
  date: string;
  amount: number;
  type: 'deposit' | 'withdraw';
  notes?: string;
}

export interface RecurringTransaction {
  id: string;
  title: string;
  amount: number;
  type: 'income' | 'expense';
  category: ExpenseCategory | IncomeSource | string;
  frequency: 'monthly' | 'weekly' | 'yearly';
  dueDay: number; // 1 - 31
  nextDueDate: string; // YYYY-MM-DD
  paymentMethod?: PaymentMethod;
  accountId?: string;
  classification?: ExpenseClassification;
  autoGenerated?: boolean;
  reminderDaysBefore?: number;
  notes?: string;
  lastPaidMonth?: string; // e.g. '2026-09'
}

export interface DebtPayment {
  id: string;
  date: string;
  amount: number;
  notes?: string;
}

export interface Debt {
  id: string;
  title: string;
  personName: string;
  type: 'payable' | 'receivable'; // payable = utang kita ke orang, receivable = piutang orang ke kita
  principalAmount: number;
  remainingAmount: number;
  dueDate: string; // YYYY-MM-DD
  notes?: string;
  payments: DebtPayment[];
  createdAt: string;
}

export interface UserSettings {
  userName: string;
  university: string;
  openingBalance: number;
  monthlyIncomeTarget: number;
  essentialExpenseTarget: number;
  desiredSavingsTarget: number;
  paydayOrAllowanceDay: number; // 1 - 31
  emergencyFundMonths: number; // e.g., 3 months
  hasCompletedOnboarding: boolean;
  selectedBudgetingMethod?: BudgetingMethodType;
  lastRecurringCheckDate?: string;
  cloudSyncUrl?: string;
  autoSyncEnabled?: boolean;
  syncIntervalSeconds?: number;
}

export type BudgetingMethodType =
  | '50_30_20'
  | '80_20'
  | 'zero_based'
  | 'debt_snowball'
  | 'debt_avalanche'
  | 'jar_system'
  | 'custom';

export interface BudgetingMethodAllocation {
  name: string;
  percentage: number;
  categories: ExpenseCategory[];
  description: string;
  color: string;
}

export interface BudgetingMethodDefinition {
  id: BudgetingMethodType;
  name: string;
  shortName: string;
  tagline: string;
  description: string;
  philosophy: string;
  idealFor: string;
  proTip: string;
  isDebtFocused?: boolean;
  allocations: BudgetingMethodAllocation[];
}

export interface FinancialHealthBreakdown {
  overallScore: number;
  rating: 'Sangat Sehat' | 'Sehat' | 'Cukup' | 'Perlu Perhatian' | 'Kritis';
  budgetScore: number; // max 25
  savingsScore: number; // max 25
  emergencyScore: number; // max 20
  discretionaryScore: number; // max 15
  debtScore: number; // max 15
  recommendations: string[];
}

export interface SmartRecommendation {
  id: string;
  type: 'warning' | 'tip' | 'praise';
  title: string;
  message: string;
  reason: string; // "Mengapa ini muncul"
  actionableStep?: string;
}

export interface AppNotification {
  id: string;
  type: 'budget' | 'recurring' | 'goal' | 'achievement' | 'system';
  title: string;
  message: string;
  date: string;
  read: boolean;
}

export interface OutboxMutation {
  id: string;
  entity: 'transaction' | 'budget' | 'goal' | 'recurring' | 'account' | 'debt' | 'settings' | 'batch';
  action: 'create' | 'update' | 'delete' | 'sync_all';
  data: any;
  timestamp: string;
  retries: number;
}

export interface DeviceSyncStatus {
  status: 'synced' | 'syncing' | 'offline' | 'pending' | 'error';
  lastSyncedAt: Date | null;
  serverIp: string | null;
  serverUrl: string | null;
  version: number;
  outboxCount: number;
  dataHash: string | null;
  errorMessage?: string | null;
  syncNow: () => Promise<void>;
  verifyIntegrity: () => Promise<{ identical: boolean; serverVersion: number; localVersion: number; serverHash: string; localHash: string }>;
  setCustomServerUrl: (url: string) => void;
  clearOutbox: () => void;
}

// 1. Perencanaan Anggaran Semester
export interface SemesterBudget {
  id: string;
  name: string; // e.g. "Semester 5 (Ganjil 2026/2027)"
  academicYear: string; // "2026/2027"
  targetUKT: number;
  monthlyLivingTarget: number;
  academicSuppliesBudget: number;
  housingBudget: number;
  otherBudget: number;
  totalMonths: number;
  startDate: string; // YYYY-MM
  endDate: string; // YYYY-MM
  notes?: string;
  createdAt: string;
}

// 2. Pelacakan Beasiswa & Bantuan Keuangan
export interface ScholarshipRequirement {
  id: string;
  title: string;
  completed: boolean;
}

export interface Scholarship {
  id: string;
  name: string; // e.g. "KIP Kuliah", "Beasiswa Bank Indonesia", "Djarum Plus"
  provider: string;
  amount: number;
  frequency: 'monthly' | 'semester' | 'yearly' | 'one_time';
  nextDisbursementDate: string; // YYYY-MM-DD
  status: 'active' | 'disbursed' | 'pending' | 'completed';
  requirements: ScholarshipRequirement[];
  notes?: string;
  createdAt: string;
}

// 3. Integrasi & Tagihan Kampus (UKT, Kartu Makan/KTM, Lab, Denda Perpus)
export interface CampusBill {
  id: string;
  title: string; // e.g. "UKT Semester 5", "Denda Buku Perpustakaan", "Biaya Modul & Praktikum"
  category: 'ukt' | 'practicum' | 'library' | 'organization' | 'meal_card' | 'other';
  amount: number;
  dueDate: string; // YYYY-MM-DD
  isPaid: boolean;
  paidDate?: string;
  paidFromAccountId?: string;
  notes?: string;
  createdAt: string;
}

// 4. Pembagian Pengeluaran P2P (Split Bill Mahasiswa) dengan QR Code & QRIS
export interface SplitBillMember {
  id: string;
  name: string;
  amount: number;
  isPaid: boolean;
  notes?: string;
}

export interface SplitBill {
  id: string;
  title: string;
  totalAmount: number;
  taxPercent: number;
  discount: number;
  date: string;
  payerAccountId?: string;
  qrisAccountName?: string;
  qrisBank?: string;
  qrisAccountNumber?: string;
  members: SplitBillMember[];
  createdAt: string;
}

// 9. Dashboard Perbandingan Harga Kebutuhan Mahasiswa
export interface PriceOption {
  label: string;
  price: number;
  isBestValue?: boolean;
}

export interface PriceComparisonItem {
  id: string;
  itemName: string;
  category: string;
  unit: string;
  studentTip: string;
  monthlySavingsPotential: number;
  options: PriceOption[];
}

// 8. Gamifikasi Kesehatan Finansial
export interface GamificationBadge {
  id: string;
  name: string;
  description: string;
  icon: string;
  unlocked: boolean;
  unlockedAt?: string;
  progress: number;
  maxProgress: number;
}

export interface GamificationQuest {
  id: string;
  title: string;
  description: string;
  rewardXP: number;
  completed: boolean;
  icon: string;
}

export interface GamificationProfile {
  level: number;
  levelTitle: string;
  currentXP: number;
  maxXPForLevel: number;
  streakDays: number;
  badges: GamificationBadge[];
  quests: GamificationQuest[];
}

